package com.oktaysadoglu.memofication.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.oktaysadoglu.memofication.db.Word;
import com.oktaysadoglu.memofication.db.UserWords;

import com.oktaysadoglu.memofication.db.WordDao;
import com.oktaysadoglu.memofication.db.UserWordsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wordDaoConfig;
    private final DaoConfig userWordsDaoConfig;

    private final WordDao wordDao;
    private final UserWordsDao userWordsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        userWordsDaoConfig = daoConfigMap.get(UserWordsDao.class).clone();
        userWordsDaoConfig.initIdentityScope(type);

        wordDao = new WordDao(wordDaoConfig, this);
        userWordsDao = new UserWordsDao(userWordsDaoConfig, this);

        registerDao(Word.class, wordDao);
        registerDao(UserWords.class, userWordsDao);
    }
    
    public void clear() {
        wordDaoConfig.getIdentityScope().clear();
        userWordsDaoConfig.getIdentityScope().clear();
    }

    public WordDao getWordDao() {
        return wordDao;
    }

    public UserWordsDao getUserWordsDao() {
        return userWordsDao;
    }

}
