package com.oktaysadoglu.memofication.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LAST_WORD_NUMBER".
 */
public class LastWordNumber {

    private Long id;
    private Integer last_number;

    public LastWordNumber() {
    }

    public LastWordNumber(Long id) {
        this.id = id;
    }

    public LastWordNumber(Long id, Integer last_number) {
        this.id = id;
        this.last_number = last_number;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLast_number() {
        return last_number;
    }

    public void setLast_number(Integer last_number) {
        this.last_number = last_number;
    }

    @Override
    public String toString() {
        return "LastWordNumber{" +
                "id=" + id +
                ", last_number=" + last_number +
                '}';
    }
}
